name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm
        git push -u origin upm
      env:
        PKG_ROOT: Packages/com.appylar.unity-sdk
    - name: Create upm git tag
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git tag $TAG upm
        git push origin --tags
      env:
        TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
